In [6]:
import numpy as np
from scipy import signal

### planta em espaço de estados

# Tank orifice diameter    (cm^2)
a1 = 0.17813919765
a2 = a1
    # Tank base area (cm^2)
A1 = 15.5179
A2 = A1
    # Gravitational acceleration (m/s^2)
g = 980.7
    # Pump flow constant ((cm^3)/sV)
km = 4.6
    # ODEs Constants
L20 = 15
L10 = ( (a2*a2)/(a1*a1) ) * L20

# State space
A11 = -1*(a1/A1)*np.sqrt(g/(2*L10))
A12 = 0
A21 = (a1/A2)*np.sqrt(g/(2*L10))
A22 = -1*(a2/A2)*np.sqrt(g/(2*L20))
B1 = (km/A1)
B2 = 0.0
x1 = 0.0    
x2 = 0.0

A = np.array([[A11, A12],[A21, A22]])
B = np.array([[B1],[B2]])
C = np.array([[1,1]])
D = np.array([[0]])

sys = signal.StateSpace(A, B, C, D)

print(sys)

StateSpaceContinuous(
array([[-0.06563478,  0.        ],
       [ 0.06563478, -0.06563478]]),
array([[0.29643186],
       [0.        ]]),
array([[1, 1]]),
array([[0]]),
dt: None
)


In [7]:
sys.to_discrete(0.1)

StateSpaceDiscrete(
array([[0.99345802, 0.        ],
       [0.00652054, 0.99345802]]),
array([[2.95461175e-02],
       [9.68565708e-05]]),
array([[1, 1]]),
array([[0]]),
dt: 0.1
)

In [10]:
### modelo discrto da planta DIFERENTE

alfa = (a1/A1)*np.sqrt(g/2*L20)
print(alfa)

beta = 3.3/A1
print(beta)

A = np.array([[np.exp(-1*alfa*0.1), 0],[alfa*0.1*np.exp(-1*alfa*0.1), np.exp(-1*alfa*0.1)]])
B = np.array([[(beta/alfa)*(1 - np.exp(-1*alfa*0.1))],[(beta/alfa)*(1 - np.exp(-1*alfa*0.1)*((alfa*0.1)+1))]])
C = np.array([[1,1]])
D = np.array([[0]])

sys = signal.StateSpace(A, B, C, D)

print(sys)

0.984521630708102
0.21265764053125746
StateSpaceContinuous(
array([[0.90623904, 0.        ],
       [0.08922119, 0.90623904]]),
array([[0.02025246],
       [0.00098059]]),
array([[1, 1]]),
array([[0]]),
dt: None
)


In [15]:
import os
import re
import math
import signal
import os

def noise(noiseProb,noiseMax):
    if int(os.urandom(1).encode('hex'),16)/255. < noiseProb:    
        i = int(os.urandom(4).encode('hex'),16) % noiseMax
        f = float(int(os.urandom(6).encode('hex'),16))
        f =  f/10000.0 - float(int(f/10000.0))
        return i+f
    else:
        return 0

In [16]:
noise(0,12)

AttributeError: 'bytes' object has no attribute 'encode'